apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-volume-claim
spec:
  storageClassName: app-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
