apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistence-volume
  labels:
    app: reticules
spec:
  storageClassName: app-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
